### ISSUE TITLE
conversion to four time periods

### ISSUE THREAD

**Issue by nsdhakar** [RSGInc/BKRCast#1]
update setup to four time periods

**Comment by nsdhakar** [comment]
Updated following scripts (823d9a2b82f8aba81c04f4322ec31b4f7f4a1a62) :

> emme_configuration.py
> input_configuration.py
> run_bkrcast.py
> scripts\bikes\bike_configuration.py
> scripts\trucks\truck_configuration.py
> scripts\supplemental\distribution.py
> scripts\WriteRoaster\RosterWriter.cs
> scripts\skimming\SkimsAndPaths.py
> scripts\archive\archive.py
> scripts\archive\revive.py
> scripts\summarize\standard\network_summary.py

**Comment by PeterVermont** [comment]
Got an error:


System.IO.FileNotFoundException: Could not find file 'E:\Projects\DaySim\regional_data\BKRCast\inputs\TAZIndex.txt'.
File name: 'E:\Projects\DaySim\regional_data\BKRCast\inputs\TAZIndex.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions o                                                                                                                                           ptions, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.FileInfo.Open(FileMode mode, FileAccess access, FileShare share)
   at DaySim.InputTester.GetValidZones() in C:\rd\DaySim\Daysim\InputTester.cs:line 48
   at DaySim.InputTester.RunTest() in C:\rd\DaySim\Daysim\InputTester.cs:line 24
   at DaySim.Engine.BeginTestInputs() in C:\rd\DaySim\Daysim\Engine.cs:line 113
   at DaySim.Engine.BeginProgram(Int32 start, Int32 end, Int32 index) in C:\rd\DaySim\Daysim\Engine.cs:line 61
   at DaySim.Program.Main(String[] args) in C:\rd\DaySim\Daysim\Program.cs:line 152


……………………………………………..
PETER ANDREWS
Senior Software Engineer

RSG
55 Railroad Row | White River Junction, VT 05001
o 802.359.6411 | m 802.356.3141
www.rsginc.com<http://www.rsginc.com/>
……………………………………………..

**Comment by PeterVermont** [comment]
Never mind – just saw readme about other inputs repo.

……………………………………………..
PETER ANDREWS
Senior Software Engineer

RSG
55 Railroad Row | White River Junction, VT 05001
o 802.359.6411 | m 802.356.3141
www.rsginc.com<http://www.rsginc.com/>
……………………………………………..

From: Peter Andrews
Sent: Thursday, November 03, 2016 9:49 AM
To: 'RSGInc/BKRCast' <reply@reply.github.com>; RSGInc/BKRCast <BKRCast@noreply.github.com>
Subject: RE: [RSGInc/BKRCast] conversion to four time periods (#1)

Got an error:


System.IO.FileNotFoundException: Could not find file 'E:\Projects\DaySim\regional_data\BKRCast\inputs\TAZIndex.txt'.
File name: 'E:\Projects\DaySim\regional_data\BKRCast\inputs\TAZIndex.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions o                                                                                                                                           ptions, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.FileInfo.Open(FileMode mode, FileAccess access, FileShare share)
   at DaySim.InputTester.GetValidZones() in C:\rd\DaySim\Daysim\InputTester.cs:line 48
   at DaySim.InputTester.RunTest() in C:\rd\DaySim\Daysim\InputTester.cs:line 24
   at DaySim.Engine.BeginTestInputs() in C:\rd\DaySim\Daysim\Engine.cs:line 113
   at DaySim.Engine.BeginProgram(Int32 start, Int32 end, Int32 index) in C:\rd\DaySim\Daysim\Engine.cs:line 61
   at DaySim.Program.Main(String[] args) in C:\rd\DaySim\Daysim\Program.cs:line 152


……………………………………………..
PETER ANDREWS
Senior Software Engineer

RSG
55 Railroad Row | White River Junction, VT 05001
o 802.359.6411 | m 802.356.3141
www.rsginc.com<http://www.rsginc.com/>
……………………………………………..

**Comment by nsdhakar** [comment]
the latest daysim works. closing this now. 823d9a2b82f8aba81c04f4322ec31b4f7f4a1a62

**Comment by nsdhakar** [comment]
The four time period model setup is not quite working. skims don't look right, reopening the issue.
