### ISSUE TITLE
returncode = 3221225477 after executing generation.py

### ISSUE THREAD

**Issue by dong-bellevue** [RSGInc/BKRCast#147]
End of 0 iteration of Daysim
 run_truck_supplemental starting
Calculating supplemental trips generated by exterals, special generators, and group quarters.
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\hdong\anaconda3\envs\BKRCast\Lib\logging\__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hdong\anaconda3\envs\BKRCast\Lib\logging\__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hdong\anaconda3\envs\BKRCast\Lib\logging\__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hdong\anaconda3\envs\BKRCast\Lib\logging\__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\Users\hdong\source\repos\bellevuewa\BKRCastCodeandTestBed\BKRCast_2044\run_bkrcast.py", line 498, in <module>
    main()
  File "C:\Users\hdong\source\repos\bellevuewa\BKRCastCodeandTestBed\BKRCast_2044\run_bkrcast.py", line 468, in main
    daysim_assignment(iteration)
  File "C:\Users\hdong\source\repos\bellevuewa\BKRCastCodeandTestBed\BKRCast_2044\scripts\logcontroller.py", line 39, in wrapper
    result = f(*args, **kwds)
  File "C:\Users\hdong\source\repos\bellevuewa\BKRCastCodeandTestBed\BKRCast_2044\run_bkrcast.py", line 190, in daysim_assignment
    run_truck_supplemental(iteration)
  File "C:\Users\hdong\source\repos\bellevuewa\BKRCastCodeandTestBed\BKRCast_2044\scripts\logcontroller.py", line 39, in wrapper
    result = f(*args, **kwds)
  File "C:\Users\hdong\source\repos\bellevuewa\BKRCastCodeandTestBed\BKRCast_2044\run_bkrcast.py", line 149, in run_truck_supplemental
    logger.info('Supplemental trip generation crashed unexpectedly. The return code is', str(returncode))
Message: 'Supplemental trip generation crashed unexpectedly. The return code is'
Arguments: ('3221225477',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\hdong\anaconda3\envs\BKRCast\Lib\logging\__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hdong\anaconda3\envs\BKRCast\Lib\logging\__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hdong\anaconda3\envs\BKRCast\Lib\logging\__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hdong\anaconda3\envs\BKRCast\Lib\logging\__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\Users\hdong\source\repos\bellevuewa\BKRCastCodeandTestBed\BKRCast_2044\run_bkrcast.py", line 498, in <module>
    main()
  File "C:\Users\hdong\source\repos\bellevuewa\BKRCastCodeandTestBed\BKRCast_2044\run_bkrcast.py", line 468, in main
    daysim_assignment(iteration)
  File "C:\Users\hdong\source\repos\bellevuewa\BKRCastCodeandTestBed\BKRCast_2044\scripts\logcontroller.py", line 39, in wrapper
    result = f(*args, **kwds)
  File "C:\Users\hdong\source\repos\bellevuewa\BKRCastCodeandTestBed\BKRCast_2044\run_bkrcast.py", line 190, in daysim_assignment
    run_truck_supplemental(iteration)
  File "C:\Users\hdong\source\repos\bellevuewa\BKRCastCodeandTestBed\BKRCast_2044\scripts\logcontroller.py", line 39, in wrapper
    result = f(*args, **kwds)
  File "C:\Users\hdong\source\repos\bellevuewa\BKRCastCodeandTestBed\BKRCast_2044\run_bkrcast.py", line 149, in run_truck_supplemental
    logger.info('Supplemental trip generation crashed unexpectedly. The return code is', str(returncode))
Message: 'Supplemental trip generation crashed unexpectedly. The return code is'
Arguments: ('3221225477',)

**Comment by dong-bellevue** [comment]
According to ChatGPT, return code 3221225477 is significant. It is equivalent to 0xC0000005, which confirms it is an access violation. Further code debugging didn't find any crash inside generation.py.

**Comment by dong-bellevue** [comment]
BTW, I never got this kind of access violation error before. Code was OK in Win10 but after the City migrated to Win11, I got this error. Not 100% sure it is the cause.

**Comment by dong-bellevue** [comment]
Through line by line test,  the following two lines created the trouble.
`import inro.emme.database.emmebank as _eb`  
`import inro.emme.desktop.app as app`

Since they are EMME packages, we need to send this issue to Bentley support.

**Comment by dong-bellevue** [comment]
EMME support suggested us to reinstall EMME and BKRCast and everything else related to BKRCast. However, after doing that the issue is still not fixed yet.

Since the subrpocess is fully executed, for now we can simply ignore this particular return code.

**Comment by dong-bellevue** [comment]
**For future verification only.**
Use `test.py` to verify if the issue is resolved, and then eliminate the special handling for return code 3221225477.
